[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "roam-mcp"
version = "0.2.0"
description = "A Model Context Protocol server for Roam Research integration with AI assistants"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Roam MCP Project Contributors"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "mcp>=1.3.0",
    "httpx>=0.24.0",
    "pydantic>=2.0.0",
    "youtube-transcript-api>=0.6.0",
    "requests>=2.28.0",
    "python-dotenv>=1.0.0",
    "trafilatura>=1.6.0",
    "unstructured[pdf]>=0.10.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
    "pylint>=2.17.0"
]

[project.scripts]
roam-mcp = "roam_mcp.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["roam_mcp"]

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pylint.messages_control]
disable = [
    "missing-docstring",
    "invalid-name"
]

[project.urls]
"Homepage" = "https://github.com/PhiloSolares/roam-mcp"
"Bug Tracker" = "https://github.com/PhiloSolares/roam-mcp/issues"